### ISSUE TITLE
Things that need to be done

### ISSUE THREAD

**Issue by marcothms** [CramMK/dotfiles#1]

**Comment by marcothms** [comment]
+ feh and a Wallpaper in dotfiles

**Comment by marcothms** [comment]
+ A fancy info bar

**Comment by marcothms** [comment]
+ New color theme

Breeze dark -> Broke?

**Comment by marcothms** [comment]
Maybe a blur instead of transparency?

https://jlk.fjfi.cvut.cz/arch/manpages/man/picom.1.html

**Comment by CramMK** [comment]
Maybe swicth to airline for vim because of Breezy

**Comment by marcothms** [comment]
Add
if [ -f ~/.zsh/zshalias_local ]; then
    source ~/.zsh/zshalias_local
fi

**Comment by marcothms** [comment]
refine picom conf
-> blur?

**Comment by marcothms** [comment]
clear dotfiles - single directories

**Comment by marcothms** [comment]
Screen brightness

**Comment by marcothms** [comment]
refine bar

**Comment by marcothms** [comment]
add screenshots to readme

**Comment by marcothms** [comment]
add chrome to laptop startup

**Comment by marcothms** [comment]
remove wlan/lan from bar -> nm-applet
